### ISSUE TITLE
Mac OS: Unable to Retrieve Terminal Pixel Dimensions Using ioctl in Neovim

### ISSUE THREAD

**Issue by fefa4ka** [Thiago4532/mdmath.nvim#2]
I'm facing an issue retrieving terminal pixel dimensions using ioctl in Neovim. While this method works in a regular terminal session on macOS and Linux using LuaJIT (with `TIOCGWINSZ = 1074295912` for Mac OS and FreeBSD), it fails within Neovim. This discrepancy makes it difficult to accurately gather terminal size information, especially pixel dimensions.

Steps to Reproduce:
* Create a Lua script that uses FFI to call `ioctl` with the `TIOCGWINSZ` request for terminal size including pixel dimensions.
* Execute the script successfully in a standard terminal session on macOS and Linux.
* Attempt to run the same script within Neovim.

Observed Behavior:
Running the script inside Neovim returns an error indicating the file descriptor is not a terminal.
Neovim abstracts terminal access in a way that makes direct ioctl calls unreliable.

**Comment by Thiago4532** [comment]
Hi, I am already aware of this!! Sadly I don't have an MacOS machine available, so I'll try setting up a virtual machine so I can do some tests. If you have know any way on how to solve this, please let me know :)

**Comment by fefa4ka** [comment]
Here is a widely used approach: https://github.com/vhyrro/hologram.nvim/blob/main/lua/hologram/state.lua
But still not work on my setup (macos, neovim in tmux)
