### ISSUE TITLE
Not working with tmux

### ISSUE THREAD

**Issue by Thiago4532** [Thiago4532/mdmath.nvim#5]
Images are deformed/empty when running inside tmux.

**Comment by m1chaelwilliams** [comment]
Hi, I got it working on my end. I've added a change to the `kitty_send` function that fixes the issue of images being empty/rendering incorrectly in tmux. I plan on submitting a pull request shortly.

![Screenshot 2024-12-23 at 3 00 38 PM](https://github.com/user-attachments/assets/a098ab42-c3fd-4fa6-92f9-63329d93dc02)

**Comment by Thiago4532** [comment]
Should be fixed by #10 and #11.
